### ISSUE TITLE
_get_block_bsfs fails when a pop has only one individual

### ISSUE THREAD

**Issue by A-J-F-Mackintosh** [DRL/gIMble#21]
When using `gIMble blocks` or `gIMble info` the function `_get_block_bsfs` cannot handle populations with only one diploid individual.

e.g. : 

If the sample file looks like:

```
1L19,acredula
1M13,acredula
DW83,fuscatus
```
Then the following error is generated when trying to get blocks:

```
[%] Building blocks : 100%|██████████████████████████████████████| 3.00/3.00 [01:07<00:00, 22.6s/it]
Traceback (most recent call last):
File "/ceph/users/amackintosh/software/gimble/gIMble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
File "/ceph/users/amackintosh/software/gimble/cli/interface.py", line 69, in main
    blocks.main(params)
File "/ceph/users/amackintosh/software/gimble/cli/blocks.py", line 65, in main
    gimbleStore.info()
File "/ceph/users/amackintosh/software/gimble/lib/gimble.py", line 1455, in info
    report += self._get_blocks_report(width)
File "/ceph/users/amackintosh/software/gimble/lib/gimble.py", line 1396, in _get_blocks_report
    bsfs_B = bsfs_to_2d(self.get_bsfs(data_type='blocks', sample_sets='B'))
File "/ceph/users/amackintosh/software/gimble/lib/gimble.py", line 1169, in get_bsfs
    bsfs = self._get_block_bsfs(sample_sets=sample_sets, population_by_letter=population_by_letter, kmax_by_mutype=kmax_by_mutype)
File "/ceph/users/amackintosh/software/gimble/lib/gimble.py", line 1213, in _get_block_bsfs
    variation = np.concatenate(variations, axis=0) # concatenate is faster than offset-indexes
File "<__array_function__ internals>", line 6, in concatenate
    ValueError: need at least one array to concatenate
```

**Comment by DRL** [comment]
For this we need to decide what to do if there is only one sample in a population.

Do we want to construct intra-population sample sets containing the same sample twice?

**Comment by DRL** [comment]
fixed
