### ISSUE TITLE
Info characters 

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#41]
On GB's machine (OSX) running 

```
./gimble info -z FILE --tree
```

yields

```Traceback (most recent call last):
  File "./gimble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/Users/s1854903/git/gIMble/cli/interface.py", line 78, in main
    info.main(params)
  File "/Users/s1854903/git/gIMble/cli/info.py", line 37, in main
    print(info)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-5: ordinal not in range(128)```

**Comment by DRL** [comment]
replace `SIGNS` with unicode expressions and works the same on my machine/the cluster.

Either need further guidance on how to reproduce or somebody else tackles this ...

**Comment by DRL** [comment]
done
