### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#51]
It is currently possible to parse more variants than can be placed in intervals.

Requires 
- `gimble._set_intervals()` to be called before `gimble._set_variants()`
- filtering of variant position array by interval position array (based on all samples)

Possibly related to Noora's issue:

```gIMble/./gIMble blocks -f -z /scratch/npoikela/montana.flavomontana.sympatric_west.all.genic.z -l 64
[+] Running 'gimble blocks'
[+] Parameters = [-l 64 -m 128 -u 3 -i 3]
[#] Preflight...
[#] Making blocks...
[%] Building blocks :   0%|                                              | 0.00/330 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "gIMble/./gIMble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(file)))
  File "/data/lohse/drosophila/analyses/18_gimble/combined_ref/gIMble/cli/interface.py", line 69, in main
    blocks.main(params)
  File "/data/lohse/drosophila/analyses/18_gimble/combined_ref/gIMble/cli/blocks.py", line 61, in main
    gimbleStore.blocks(parameterObj)
  File "/data/lohse/drosophila/analyses/18_gimble/combined_ref/gIMble/lib/gimble.py", line 1039, in blocks
    self._make_blocks(parameterObj)
  File "/data/lohse/drosophila/analyses/18_gimble/combined_ref/gIMble/lib/gimble.py", line 2659, in _make_blocks
    block_sites = genotype_to_mutype_array(sa_sample_set_genotype_array, idx_block_sites_in_pos, block_sites, debug)
  File "/data/lohse/drosophila/analyses/18_gimble/combined_ref/gIMble/lib/gimble.py", line 462, in genotype_to_mutype_array
    block_sites[idx_block_sites_in_pos] = szudzik_pairing(folded_minor_allele_counts) + 2               # add 2 so that not negative for bincount
ValueError: NumPy boolean array indexing assignment cannot assign 616352 input values to the 621913 output values where the mask is true```

**Comment by DRL** [comment]
Refactored `gimble.Store._set_variants()`to now 
- first parse BED intervals and then 
- parse VCF while using
- `*_get_interval_coordinates_for_sample_set()` to fetch BED intervals which
- are used to decide which variant records get save/counted

**Comment by DRL** [comment]
fixed in https://github.com/DRL/gIMble/commit/65ef9e5ac52bbdfe4fedc4511957f64c179a4d56
