### ISSUE TITLE
gIMble query error

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#76]
```
./gIMble query -w -z ~/temp_zarr_store.nosync/gimble.2chr_1M.z --bed
[+] Getting data for BED ...
[%] Preparing data...: 100%|█████████████████████████████████████| 2.00/2.00 [00:00<00:00, 71.6it/s]
[+] Calculating popgen metrics ...
Traceback (most recent call last):
  File "/Users/s1854903/git/gIMble/./gIMble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/Users/s1854903/git/gIMble/cli/interface.py", line 69, in main
    query.main(params)
  File "/Users/s1854903/git/gIMble/cli/query.py", line 85, in main
    gimbleStore.query(
  File "/Users/s1854903/git/gIMble/lib/gimble.py", line 2033, in query
    self._write_window_bed(version)
  File "/Users/s1854903/git/gIMble/lib/gimble.py", line 2803, in _write_window_bed
    int_bed = np.vstack([starts, ends, index, pos_mean, pos_median, pop_metrics, balance, mse_sample_set_cov]).T
  File "<__array_function__ internals>", line 5, in vstack
  File "/Users/s1854903/miniconda3/envs/gimble_dev_msprime/lib/python3.9/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 390 and the array at index 5 has size 256```

**Comment by DRL** [comment]
see latest release
