### ISSUE TITLE
gimble info error

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#91]
I change a bigger vcf file and run through preprocess parse blocks windows

But when I run gimble info from your instruction 

./gimble info -z analysis.z 

it reports
[+] Running 'gimble info' ...
[+] Getting report. This might take a while ...
[+]      Getting storage info ...
[+]      Getting parse info...
[+]      Getting blocks info...
Traceback (most recent call last):
  File "./gIMble/gimble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/data/01/user214/11.gimble/gIMble/cli/interface.py", line 93, in main
    runner.main(params)
  File "/data/01/user214/11.gimble/gIMble/cli/info.py", line 47, in main
    tree=parameterObj.tree)
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 4057, in info
    report += self._get_blocks_report(width)
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 3946, in _get_blocks_report
    BRMs = self._get_blocks_report_metrics()
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 3912, in _get_blocks_report_metrics
    self._get_variation(data_type="blocks", sample_sets=sample_sets),
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 3306, in _get_variation
    variation = np.concatenate(variations, axis=0)
  File "\<\__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

I do not know why it occured.
my gimble.samples.csv:

kem0,kempi
rus0,russatus

**Comment by DRL** [comment]
Looks like there are no blocks. Could that be?

**Comment by DRL** [comment]
Function `_get_blocks_report_metrics()` needs to error gracefully if there are no blocks

**Comment by gotouerina** [comment]
> ./gimble info -z analysis.z

I re-checked my file.
In analysis-z folder, I found block folder and it is not empty. However, I found that the binary file of each chr is almost 0, 24 or 48 bytes.

What can lead to this situation?

**Comment by gotouerina** [comment]
> Looks like there are no blocks. Could that be?

To test whether blocks exist, I run ./gIMble/gimble blocks -z analysis.z -l 1 

and it Reports

[+] Running 'gimble blocks' ...
[X] Gimble store '/data/01/user214/acomysvcf/11.gimble/analysis.z' already contains blocks.
[X] These blocks => '/data/01/user214/acomysvcf/11.gimble/gIMble/gimble blocks --zstore /data/01/user214/acomysvcf/11.gimble/analysis.z --block_length 64 --block_span 128 --block_max_multiallelic 3 --block_max_missing 3 --overwrite False '
[X] Please specify '--force' to overwrite.

So I run

./gIMble/gimble blocks -z analysis.z -l 1 --force 

But reports

[+] Running 'gimble blocks' ...
[-] Gimble store '/data/01/user214/acomysvcf/11.gimble/analysis.z' already contains blocks. But these will be overwritten...
Traceback (most recent call last):
  File "./gIMble/gimble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/data/01/user214/acomysvcf/11.gimble/gIMble/cli/interface.py", line 93, in main
    runner.main(params)
  File "/data/01/user214/acomysvcf/11.gimble/gIMble/cli/blocks.py", line 57, in main
    overwrite=parameterObj.overwrite)
  File "/data/01/user214/acomysvcf/11.gimble/gIMble/lib/gimble.py", line 1484, in blocks
    overwrite,
  File "/data/01/user214/acomysvcf/11.gimble/gIMble/lib/gimble.py", line 1457, in _preflight_blocks
    self._del_data_and_meta(windows_meta["windowsum_raw_tally_key"])
  File "/data/00/user/user214/miniconda3/envs/gimble/lib/python3.7/site-packages/zarr/attrs.py", line 74, in __getitem__
    return self.asdict()[item]
KeyError: 'windowsum_raw_tally_key'

I do not know whether it is a new bug

**Comment by DRL** [comment]
I added more code to deal with gimble stores that don't have enough blocks.

The last bit about `windowsum_raw_tally_key` was a bug and is now fixed as well.
