### ISSUE TITLE
KeyError: 'blocks/Contig1/1/starts'

### ISSUE THREAD

**Issue by gotouerina** [DRL/gIMble#98]
Using ./gIMble/gimble windows -z analysis.z  -w 500

[+] Running 'gimble windows' ...
[+] Making windows along 29 sequences (5 sequences excluded)
[%] Progress:  66%|████████████████████████████████                 | 19/29 [00:03<00:02,  4.91it/s]
Traceback (most recent call last):
  File "./gIMble/gimble", line 8, in <module>
    main(os.path.dirname(os.path.realpath(__file__)))
  File "/data/01/user214/11.gimble/gIMble/cli/interface.py", line 93, in main
    runner.main(params)
  File "/data/01/user214/11.gimblegIMble/cli/windows.py", line 44, in main
    overwrite=parameterObj.overwrite)
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 1510, in windows
    config = self._make_windows(config)
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 3662, in _make_windows
    sample_sets=config["sample_sets"], sequences=[seq_name]
  File "/data/01/user214/11.gimble/gIMble/lib/gimble.py", line 3627, in _get_block_sample_set_idxs
    np.full(self.data[key].shape[0], int(sample_set_idx))
  File "/data/00/user/user214/miniconda3/envs/gimble/lib/python3.7/site-packages/zarr/hierarchy.py", line 458, in __getitem__
    raise KeyError(item)
KeyError: 'blocks/Contig1/1/starts'

I think this is caused by there is no blocks in contig1 for there is no varaints detected in contig1. Is it true?

**Comment by gotouerina** [comment]
If there is too small variants in one contig or one chr, what should I do to delete this contig?

**Comment by gotouerina** [comment]
I think delete the data in folder seqs is true, isn't it ?

**Comment by DRL** [comment]
> I think delete the data in folder seqs is true, isn't it ?

No. You can control which sequences get used in gimble by removing lines from the `genomefile` when running `parse`. If you want to remove `Contig1`, just remove it from the `genomefile` and re-run `parse`.

If you delete random things from the gimble store you will break the store. Don't do that.
